# Generated by Django 3.2 on 2022-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=50, unique=True)),
                ('service_description', models.CharField(max_length=200, unique=True)),
                ('service_price', models.FloatField()),
            ],
        ),
    ]
